force-app/main/default/objects/Account/recordTypes/Commercial.recordType-meta.xml
<RecordType>
    <fullName>Commercial</fullName>
    <active>true</active>
    <description>A restaurant, grocery, or other business customer.</description>
    <label>Commercial</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <description>An individual retail customer.</description>
    <label>Individual</label>
</RecordType>

force-app/main/default/objects/Order_Summary__c/Order_Summary__c.object-meta.xml
<CustomObject>
    <description>Summary of all order details for this customer in a given month.</description>
    <label>Order Summary</label>
    <nameField>
        <label>Order Summary Period</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Summary__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <description>The customer Account this Summary belongs to.</description>
    <inlineHelpText>The customer Account this Summary belongs to.</inlineHelpText>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Summaries</relationshipLabel>
    <relationshipName>Order_Summaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Summary__c/fields/End_of_Period__c.field-meta.xml
<CustomField>
    <fullName>End_of_Period__c</fullName>
    <description>The ending of the time period this record summarizes.</description>
    <inlineHelpText>The ending of the time period this record summarizes.</inlineHelpText>
    <label>End of Period</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Summary__c/fields/Number_of_Orders__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Orders__c</fullName>
    <description>How many orders were placed during this time period.</description>
    <inlineHelpText>How many orders were placed during this time period.</inlineHelpText>
    <label>Number of Orders</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Summary__c/fields/Start_of_Period__c.field-meta.xml
<CustomField>
    <fullName>Start_of_Period__c</fullName>
    <description>The beginning of the time period this record summarizes.</description>
    <inlineHelpText>The beginning of the time period this record summarizes.</inlineHelpText>
    <label>Start of Period</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Summary__c/fields/Value_of_Goods_Sold__c.field-meta.xml
<CustomField>
    <fullName>Value_of_Goods_Sold__c</fullName>
    <description>The total value of orders placed in this time period.</description>
    <inlineHelpText>The total value of orders placed in this time period.</inlineHelpText>
    <label>Value of Goods Sold</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CustomerGenerator.cls
/**
 * Knows how to generate fake Customer records.
 */
public with sharing class CustomerGenerator implements Queueable {

	public static final Integer MONTHS_OF_DATA = 24;

	private final Integer howMany;
	private final Integer fileNumber;
	private final Integer offset;

	private List<Account> accountsToInsert = new List<Account>();
	private List<Contact> contactsToInsert = new List<Contact>();
	private List<Order_Summary__c> orderSummariesToInsert = new List<Order_Summary__c>();

	private Map<String, Id> recordTypes {
		get {
			if(recordTypes == null) {
				recordTypes = new Map<String, Id>();
				for(RecordType recordType : [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = 'Account']) {
					recordTypes.put(recordType.DeveloperName, recordType.Id);
				}
			}
			return recordTypes;
		}
		set;
	}

	public CustomerGenerator(Integer howMany, Integer fileNumber, Integer offset) {
		this.howMany = howMany;
		this.fileNumber = fileNumber;
		this.offset = offset;
	}

	public void execute(QueueableContext qc) {

		/*
		 * Grab data from one of our dummy data files, and parse it into useful records.
		 */
		String resourceName = 'customers' + fileNumber;
		List<List<String>> records = CsvReader.readIETFRFC4180CSVFile([SELECT Body FROM StaticResource WHERE Name = :resourceName].Body);
		System.debug(LoggingLevel.WARN, records.size());
		records.remove(0); // drop the header row
		for(Integer i = offset, j = offset + howMany; i < j; i++) {
			parseRow(records[i]);
		}

		if(!accountsToInsert.isEmpty()) {
			insert accountsToInsert;
		}

		if(!contactsToInsert.isEmpty()) {
			for(Contact c : contactsToInsert) {
				c.AccountId = c.Account.Id; // copy the Id value over now that the parent Account was persisted
			}
			insert contactsToInsert;
		}

		if(!orderSummariesToInsert.isEmpty()) {
			for(Order_Summary__c summary : orderSummariesToInsert) {
				summary.Customer__c = summary.Customer__r.Id; // copy the Id value over now that the parent Account was persisted
			}
			insert orderSummariesToInsert;
		}
	}

	private void parseRow(List<String> cells) {

		// id(0),first_name(1),last_name(2),email(3),company(4),phone(5),street(6),city(7),state(8),country(9),postal_code(10),commercial(11)

		// determine if this is a commercial customer or an individual
		Boolean isCommercial = Boolean.valueOf(cells[11]);

		// set up the Account record
		Account customer = new Account(
			Name = isCommercial ? cells[4] : cells[2] + ', ' + cells[1],
			RecordTypeId = isCommercial ? recordTypes.get('Commercial') : recordTypes.get('Individual'),
			BillingStreet = cells[6],
			BillingCity = cells[7],
			BillingCountry = cells[9],
			BillingPostalCode = cells[10],
			Phone = cells[5]
		);
		accountsToInsert.add(customer);

		// if individual, set up a Contact record
		if(!isCommercial) {
			contactsToInsert.add(
				new Contact(
					FirstName = cells[1],
					LastName = cells[2],
					Email = cells[3],
					Phone = cells[5],
					Account = customer
				)
			);
		}

		//set up Order Summary records
		buildOrderSummaries(customer);
	}

	private void buildOrderSummaries(Account customer) {

		for(Integer i = 1; i <= MONTHS_OF_DATA; i++) {
			Datetime marker = System.now().addMonths(-1 * i);
			orderSummariesToInsert.add(
				new Order_Summary__c(
					Name = marker.yearGmt() + '-' + marker.monthGmt(),
					Start_of_Period__c = marker.date().toStartOfMonth(),
					End_of_Period__c = marker.date().toStartOfMonth().addDays(Date.daysInMonth(marker.yearGmt(), marker.monthGmt())),
					Customer__r = customer,
					Number_of_Orders__c = (100 * Math.random()).intValue(),
					Value_of_Goods_Sold__c = (10000 * Math.random()).intValue()
				)
			);
		}
	}
}