force-app/main/default/objects/Tier__c/Tier__c.object-meta.xml
<CustomObject>
    <description>Represents the volume of business done with a customer.</description>
    <label>Tier</label>
    <nameField>
        <label>Tier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tier__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>How much of a discount being in this Tier provides.</description>
    <inlineHelpText>How much of a discount being in this Tier provides.</inlineHelpText>
    <label>Discount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/DataGenerator.cls
/**
 * Generates records to support exercises in this repo.
 */
public with sharing class DataGenerator {

	public static void populateDataModel() {

		populateAccountTiers();
		populateCustomersAndOrderSummaries();
	}

	private static void populateAccountTiers() {

		insert new List<Tier__c>{
			new Tier__c(Name='Bronze',Discount__c=0.00),
			new Tier__c(Name='Silver',Discount__c=0.01),
			new Tier__c(Name='Gold',Discount__c=0.03)
		};
	}

	private static void populateCustomersAndOrderSummaries() {

		// we have to break this out into a few execution contexts to get all the records we want (100,000 records)
		System.enqueueJob(new CustomerGenerator(384,1,0));
		System.enqueueJob(new CustomerGenerator(384,1,384));
		System.enqueueJob(new CustomerGenerator(232,1,768));
		System.enqueueJob(new CustomerGenerator(384,2,0));
		System.enqueueJob(new CustomerGenerator(384,2,384));
		System.enqueueJob(new CustomerGenerator(232,2,768));
		System.enqueueJob(new CustomerGenerator(384,3,0));
		System.enqueueJob(new CustomerGenerator(384,3,384));
		System.enqueueJob(new CustomerGenerator(232,3,768));
		System.enqueueJob(new CustomerGenerator(384,4,0));
		System.enqueueJob(new CustomerGenerator(384,4,384));
		System.enqueueJob(new CustomerGenerator(232,4,768));
	}

}